name: CD Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to PRODUCTION S3 Bucket
        # Deploy to your final, customer-facing production S3 bucket
        run: aws s3 sync . s3://<YOUR-PRODUCTION-S3-BUCKET-NAME> --exclude ".git/*" --delete
        
      - name: Invalidate PRODUCTION CloudFront Cache
        # Use the CloudFront ID for your live production site
        run: aws cloudfront create-invalidation --distribution-id <YOUR-PRODUCTION-CLOUDFRONT-ID> --paths "/*"