name: Deploy Website to S3

# 1. Triggers the workflow on pushes to the main branch
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Defines a single job named 'deploy'
jobs:
  deploy:
    # 2. Configure the environment
    runs-on: ubuntu-latest
    
    # 3. Steps involved in the job
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # (Optional) Step 2: Build your static assets (e.g., for a React/Vue app)
      # - name: Install Dependencies
      #   run: npm install
      # - name: Build Static Files
      #   run: npm run build
      
      # Step 3: Configure AWS Credentials for the workflow
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # IMPORTANT: These must be set as Secrets in your GitHub repository
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # The AWS region where your S3 bucket is located
          aws-region: us-east-1 
          
      # Step 4: Run the S3 sync command
      - name: Sync files to S3 Bucket
        run: |
          aws s3 sync \
            # Source: The local directory containing files to sync. Use 'dist/' or 'build/' if you have a build step.
            ./ \
            # Destination: Replace YOUR-S3-BUCKET-NAME with your actual bucket name
            s3://${{ secrets.travel-agency-staging-site }} \
            # Standard flags for website sync:
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --acl public-read # Makes files publicly readable for static website hosting